# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.id = QtWidgets.QLineEdit(Form)
        self.id.setEnabled(True)
        self.id.setReadOnly(True)
        self.id.setObjectName("id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.id)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.roasting = QtWidgets.QComboBox(Form)
        self.roasting.setObjectName("roasting")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.roasting)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.shape = QtWidgets.QComboBox(Form)
        self.shape.setObjectName("shape")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.shape)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.description = QtWidgets.QPlainTextEdit(Form)
        self.description.setObjectName("description")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.description)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.price = QtWidgets.QDoubleSpinBox(Form)
        self.price.setMaximum(1000000.0)
        self.price.setObjectName("price")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.price)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.size = QtWidgets.QDoubleSpinBox(Form)
        self.size.setMaximum(1000000.0)
        self.size.setObjectName("size")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.size)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.save_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавить / Изменить информацию"))
        self.label.setText(_translate("Form", "id:"))
        self.id.setText(_translate("Form", "1"))
        self.label_2.setText(_translate("Form", "name:"))
        self.label_3.setText(_translate("Form", "roasting:"))
        self.label_4.setText(_translate("Form", "shape:"))
        self.label_5.setText(_translate("Form", "description:"))
        self.label_6.setText(_translate("Form", "price:"))
        self.label_7.setText(_translate("Form", "size:"))
        self.save_btn.setText(_translate("Form", "Сохранить"))
